services:
  backend:
    build: .
    container_name: backend
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/final
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - finalnet

  reco:
    image: ass6:front
    container_name: fastapi-reco
    env_file:
      - secrets/secrets.env
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://127.0.0.1:9000/api/v1/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - finalnet

  mongo:
    image: mongo:8.0.13
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./vol/final:/data/final
    command: sh -c "mongod --bind_ip_all & sleep 5 && mongorestore --drop --db final /data/final && tail -f /dev/null"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "'db.adminCommand({ ping: 1 })'" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - finalnet

  redis:
    image: redis:8.2.1
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 1s
      timeout: 1s
      retries: 1
      start_period: 5s
    networks:
      - finalnet

networks:
  finalnet:
    driver: bridge




