spring:
  application:
    name: FinalProjectADB
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: final
      auto-index-creation: true
    redis:
      url: redis://localhost:6379
      username: client
      password: client
logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.query: DEBUG


server:
  port: 8080